### ISSUE TITLE
coercing numeric scalar to string

### ISSUE THREAD

**Issue by alexdilley** [arc-repos/arc-parser#7]
Given the following input:

```
@section
SLACK_CLIENT_ID 123456789012.123456789012
```

the value is parsed as a number and rounded:

```js
{ section: [ [ 'SLACK_CLIENT_ID', 123456789012.12346 ] ] }
```

How can the value be coerced to a string?

**Comment by brianleroux** [comment]
Ah! We had this same issue. Slacks id system is a number format unfortunately not currently supported (well) by most programming languages.

**Comment by brianleroux** [comment]
Whoops sorry on a phone! Anyhow here's a blog if you're morbidly curious why this happens. https://steve.hollasch.net/cgindex/coding/ieeefloat.html

To fix we quoted the value BUT this means you need to strip those quotes when you read the value.

**Comment by alexdilley** [comment]
Was going to say that you must've stumbled on this seeing as you advocate Slack integration :)

Yep, my intermediary solution was quoting too; just thought there may be an alternative.

Thanks for your quick response!

**Comment by alexdilley** [comment]
Sorry to comment on the back of this but did you also have trouble with the browser accepting the cookie [you presumably] _set_ and returned in a `302` redirect back to your app as a consequence of a successful negotiation with Slack?

i.e.
```js
const result = await slack.oauth.access({ client_id, client_secret, code })
if (result.ok) {
  ...
  session.userId = result.user.id;
  session.teamId = result.team.id;
  const cookie = await arc.http.session.write(session);
  return { cookie, status: 302, location: '/path/to/resource/under/client/app' };
}
```

The response contains a `Set-Cookie` header, but the browser appears to ignore it. I don't know if that's because the oauth flow has hopped between several domains: I see the cookie's `SameSite` is set to `lax` in @architect/functions code, however (possibly irrelevant).

No matter if you haven't seen this given it's likely completely unrelated to arc! But thought I'd ask on the off-chance.

**Comment by alexdilley** [comment]
The Lambda function resides on a different domain from the client app – at least in development (I'm using ngrok to expose a redirect endpoint to Slack that tunnels to my arc `sandbox`) – so suspect that may be problematic.

**Comment by alexdilley** [comment]
So since the cookie is issued by an `*.ngrok.io` tunnel I've spun-up so that Slack can make redirect requests, the only "solution" I could come up with is to remove the `SameSite` cookie attribute, add an `Access-Control-Allow-Credentials: true` header to CORS responses and make XHR requests from the browser with the `credentials: 'include'`/`withCredentials: true` param set. Although this is all local dev, this feels massively off: ideally I'd use a [webpack-dev-server] proxy, avoiding CORS concerns, but that doesn't transmit cookies for the proxied domain.

(I've been hacking around with the `sandbox` route registration code [here-ish](https://github.com/arc-repos/architect/blob/c9a11994e1e6788d4f6e2cf405164b9eb0033e84/src/sandbox/http/register-route.js#L46).)

I would certainly be curious to know how you handled local development with 'Sign in with Slack' integration (if you did)!

**Comment by brianleroux** [comment]
We did! We didn't have any of these issues but we used env vars because we just ran locally without a proxy. The bot code however we ran in staging to test it and not local. (But you could do the proxy given the bot code isn't doing anything with cookies.)

To work local w the sandbox we had env vars and used the `redirect_uri` to redirect back to `http://localhost:3000` … think thats it. If you can't get that going lmk and I'll whip up an example app!
